[smtp]
# Настройки вашего SMTP-провайдера
server     = "smtp.gmail.com"
port       = 465
password   = "bhdtgtwclixuijmx"
user       = "testforproject123456789@gmail.com"
from_email = "testforproject123456789@gmail.com"