[smtp]
# Настройки вашего SMTP-провайдера
server     = "smtp.gmail.com"      # SMTP-сервер (пример: Gmail)
port       = 465                   # Порт (обычно 465 для SSL)
password   = "bhdtgtwclixuijmx"      # Пароль или app-password
from_email = "testforproject123456789@gmail.com"   # От кого высылается письмо